#!/usr/bin/env python3
"""One-command ML pipeline for LOFOP: data -> check -> train -> detect -> report.

Runs the whole workflow in the right order with defaults that actually learn
(one focused class instead of 80 spread over too few images):

    python pipeline.py --device cuda            # full pipeline, good defaults
    python pipeline.py --device cuda --fast     # quicker settings first
    python pipeline.py --stage train            # re-run a single stage
    python pipeline.py --classes person car     # choose the classes

Stages:

1. data    - build a focused dataset. Reuses images you already downloaded
             (data/coco) by filtering the annotation JSON locally -- no new
             download. Falls back to fetching COCO128 if nothing is there.
2. check   - validate the dataset and render a few ground-truth images so you
             can SEE the labels are right before spending GPU time.
3. train   - train + evaluate with the classic training log; weights land in
             results/checkpoints/best.pt, metrics in results/accuracy.*.
4. detect  - run the trained model on val images; annotated pictures in
             results/detections/.
5. report  - print the outcome, best epoch, and where every artifact lives;
             render charts when matplotlib is available.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "scripts"))

RESULTS = ROOT / "results"
CONFIG_PATH = ROOT / "configs" / "pipeline.yaml"
STAGES = ("data", "check", "train", "detect", "report")


def banner(index: int, name: str, detail: str = "") -> None:
    extra = f"  ({detail})" if detail else ""
    print(f"\n=== [{index}/{len(STAGES)}] {name.upper()}{extra} ===", file=sys.stderr)


def _read_config() -> dict:
    import yaml

    if not CONFIG_PATH.is_file():
        raise SystemExit("configs/pipeline.yaml missing -- run the data stage first")
    return yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))


# -- stage 1: data ----------------------------------------------------------

def stage_data(args) -> None:
    banner(1, "data", f"classes: {', '.join(args.classes)}")
    src = ROOT / "data" / "coco"
    if (src / "train.json").is_file():
        # Filter the already-downloaded annotations locally (instant, no network).
        import get_coco

        for split in ("train", "val"):
            coco = json.loads((src / f"{split}.json").read_text(encoding="utf-8"))
            names = {c["name"] for c in coco["categories"]}
            unknown = [c for c in args.classes if c not in names]
            if unknown:
                raise SystemExit(f"Unknown class name(s): {unknown}")
            categories, annotations, images = get_coco._filter(coco, args.classes)
            subset = {"images": images, "annotations": annotations, "categories": categories}
            out = src / f"pipeline_{split}.json"
            out.write_text(json.dumps(subset), encoding="utf-8")
            print(f"  {split}: {len(images)} images, {len(annotations)} boxes -> {out.name}",
                  file=sys.stderr)
        train_source = src / "pipeline_train.json"
        val_source = src / "pipeline_val.json"
        image_root = src / "images"
    else:
        # Nothing downloaded yet: grab the small COCO128 set (a few MB).
        print("  data/coco not found; fetching COCO128 instead", file=sys.stderr)
        import get_coco128

        code = get_coco128.main(["--classes", *args.classes])
        if code != 0:
            raise SystemExit(code)
        base = ROOT / "data" / "coco128"
        train_source, val_source = base / "train.json", base / "val.json"
        image_root = base / "images"

    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(
        f"# Auto-generated by pipeline.py (classes: {args.classes})\n"
        "data_format: coco\n"
        f"train_source: {train_source.relative_to(ROOT).as_posix()}\n"
        f"val_source: {val_source.relative_to(ROOT).as_posix()}\n"
        f"image_root: {image_root.relative_to(ROOT).as_posix()}\n",
        encoding="utf-8",
    )
    print(f"  config -> {CONFIG_PATH.relative_to(ROOT)}", file=sys.stderr)


# -- stage 2: check -----------------------------------------------------------

def stage_check(args) -> None:
    banner(2, "check")
    from lofop.data import load_dataset, validate_dataset, visualize_dataset

    cfg = _read_config()
    for split in ("train_source", "val_source"):
        dataset = load_dataset("coco", ROOT / cfg[split], image_root=ROOT / cfg["image_root"])
        report = validate_dataset(dataset, check_images=False)
        boxes_per_image = dataset.num_annotations / max(len(dataset), 1)
        print(
            f"  {split.split('_')[0]}: {len(dataset)} images, {dataset.num_annotations} boxes "
            f"({boxes_per_image:.1f}/image), {len(dataset.categories)} classes -> "
            f"{'OK' if report.ok else 'ISSUES: ' + report.summary()}",
            file=sys.stderr,
        )
    gt_dir = RESULTS / "gt_samples"
    val = load_dataset("coco", ROOT / cfg["val_source"], image_root=ROOT / cfg["image_root"])
    paths = visualize_dataset(val, gt_dir, limit=4)
    print(f"  wrote {len(paths)} ground-truth previews -> {gt_dir.relative_to(ROOT)}/ "
          "(open them: boxes should sit on real objects)", file=sys.stderr)


# -- stage 3: train ------------------------------------------------------------

def stage_train(args) -> None:
    checkpoint = None
    if args.finetune:
        checkpoint = RESULTS / "checkpoints" / "best.pt"
        if not checkpoint.is_file():
            raise SystemExit(
                "--finetune needs existing weights at results/checkpoints/best.pt -- "
                "run a training first (python pipeline.py --stage train)"
            )
    banner(
        3, "train",
        f"variant {args.variant}, {args.epochs} epochs @ {args.acc_size}px, "
        f"batch {args.batch_size}, lr {args.lr}, device {args.device}"
        + (", fine-tuning from best.pt" if checkpoint else ""),
    )
    from lofop_bench import run_accuracy

    cfg = _read_config()
    result = run_accuracy(
        RESULTS, variant=args.variant, device=args.device, epochs=args.epochs,
        image_size=args.acc_size, batch_size=args.batch_size, lr=args.lr,
        workers=args.workers, checkpoint=checkpoint, data_format="coco",
        train_source=str(ROOT / cfg["train_source"]),
        val_source=str(ROOT / cfg["val_source"]),
        image_root=str(ROOT / cfg["image_root"]),
        limit_train=args.limit_train, limit_val=args.limit_val,
    )
    print(result.to_markdown())


# -- stage 4: detect -------------------------------------------------------------

def stage_detect(args) -> None:
    banner(4, "detect")
    import detect_sample

    code = detect_sample.main([
        "--data-config", str(CONFIG_PATH), "--variant", args.variant,
        "--size", str(args.acc_size), "--limit", "8",
        "--score-threshold", str(args.score_threshold),
    ])
    if code != 0:
        raise SystemExit(code)


# -- stage 5: report --------------------------------------------------------------

def stage_report(args) -> None:
    banner(5, "report")
    accuracy_file = RESULTS / "accuracy.json"
    if not accuracy_file.is_file():
        print("  no accuracy.json yet -- run the train stage", file=sys.stderr)
        return
    accuracy = json.loads(accuracy_file.read_text(encoding="utf-8"))
    history_file = RESULTS / "accuracy_history.json"
    best = None
    if history_file.is_file():
        history = json.loads(history_file.read_text(encoding="utf-8"))
        scored = [h for h in history if h.get("map50") is not None]
        if scored:
            best = max(scored, key=lambda h: h["map50"])
    print(f"  dataset      : {accuracy['dataset']} ({accuracy['num_classes']} classes)")
    print(f"  model        : lofop-detect-{accuracy['variant']} @ {accuracy['image_size']}px")
    print(f"  final mAP@50 : {accuracy['map50']:.4f}   precision {accuracy['precision']:.4f}"
          f"   recall {accuracy['recall']:.4f}   F1 {accuracy['f1']:.4f}")
    if best:
        print(f"  best mAP@50  : {best['map50']:.4f} at epoch {best['epoch']}")
    print("  artifacts:")
    for label, path in [
        ("metrics", "results/accuracy.md"),
        ("per-epoch history", "results/accuracy_history.json"),
        ("weights", "results/checkpoints/best.pt"),
        ("detections", "results/detections/"),
        ("ground-truth previews", "results/gt_samples/"),
    ]:
        print(f"    {label:<22} {path}")
    try:
        from lofop_bench.accuracy import AccuracyResult
        from lofop_bench.plots import plot_accuracy_curve, render_summary_image
        from lofop_bench.environment import capture

        if history_file.is_file():
            curve = plot_accuracy_curve(
                json.loads(history_file.read_text(encoding="utf-8")), RESULTS
            )
            if curve:
                print(f"    mAP-vs-epoch curve     {curve.relative_to(ROOT)}")
        summary = render_summary_image(
            RESULTS, environment=capture(), accuracy=AccuracyResult(**accuracy),
        )
        print(f"    summary image          {summary.relative_to(ROOT)}")
    except (RuntimeError, ImportError):
        print("    (install matplotlib for charts: pip install -r requirements-plots.txt)")


# -- entry point --------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="LOFOP end-to-end ML pipeline.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--stage", choices=("all", *STAGES), default="all")
    parser.add_argument("--classes", nargs="+", default=["person"],
                        help="focused classes; few classes + many images = real accuracy")
    parser.add_argument("--device", default="auto", choices=["auto", "cpu", "cuda"])
    parser.add_argument("--fast", action="store_true",
                        help="quicker settings (fewer epochs, smaller images/subset)")
    parser.add_argument("--variant", default="n")
    parser.add_argument("--finetune", action="store_true",
                        help="continue from results/checkpoints/best.pt with a lower LR "
                             "instead of training from scratch (same variant + classes)")
    parser.add_argument("--epochs", type=int, default=None)
    parser.add_argument("--acc-size", type=int, default=None)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--lr", type=float, default=None)
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument("--limit-train", type=int, default=None)
    parser.add_argument("--limit-val", type=int, default=500)
    parser.add_argument("--score-threshold", type=float, default=0.25)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    # Mode defaults: --fast for iteration, full for a proper run. Fine-tuning
    # continues from trained weights, so it uses a gentler learning rate.
    if args.epochs is None:
        args.epochs = 30 if args.fast else 80
    if args.acc_size is None:
        args.acc_size = 416 if args.fast else 512
    if args.limit_train is None:
        args.limit_train = 1500 if args.fast else 4000
    if args.lr is None:
        args.lr = 0.002 if args.finetune else 0.01

    runners = {
        "data": stage_data, "check": stage_check, "train": stage_train,
        "detect": stage_detect, "report": stage_report,
    }
    selected = STAGES if args.stage == "all" else (args.stage,)
    for name in selected:
        runners[name](args)
    print("\nPipeline complete.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
