#!/usr/bin/env python3
"""Download COCO128 and arrange it as two LOFOP YOLO dataset roots.

COCO128 is a 128-image subset of COCO (~6 MB) -- the standard "does my pipeline
work at all" dataset. This script downloads it, splits it into train/val, and
writes the layout LOFOP's YOLO loader expects::

    data/coco128/train/{classes.txt, images/, labels/}
    data/coco128/val/{classes.txt, images/, labels/}

plus ``configs/coco128.yaml`` pointing at them. Run once, then benchmark with
``--data-config configs/coco128.yaml``.
"""

from __future__ import annotations

import argparse
import io
import shutil
import sys
import urllib.request
import zipfile
from pathlib import Path

COCO128_URL = "https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip"

# The 80 COCO class names, in the canonical order YOLO indices use.
COCO_CLASSES = [
    "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train", "truck",
    "boat", "traffic light", "fire hydrant", "stop sign", "parking meter", "bench",
    "bird", "cat", "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra",
    "giraffe", "backpack", "umbrella", "handbag", "tie", "suitcase", "frisbee",
    "skis", "snowboard", "sports ball", "kite", "baseball bat", "baseball glove",
    "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
    "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange",
    "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair", "couch",
    "potted plant", "bed", "dining table", "toilet", "tv", "laptop", "mouse",
    "remote", "keyboard", "cell phone", "microwave", "oven", "toaster", "sink",
    "refrigerator", "book", "clock", "vase", "scissors", "teddy bear",
    "hair drier", "toothbrush",
]

REPO_ROOT = Path(__file__).resolve().parent.parent


def _download(url: str) -> bytes:
    print(f"Downloading {url} ...", file=sys.stderr)
    # A browser-like User-Agent avoids GitHub's 403 for the default urllib agent.
    request = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (lofop-bench)"})
    with urllib.request.urlopen(request) as response:  # noqa: S310 (trusted release asset)
        return response.read()


def _find_split_dirs(extracted: Path) -> tuple[Path, Path]:
    """Locate images/ and labels/ inside the extracted COCO128 tree."""
    images = next(extracted.rglob("images"))
    # The train2017 subdir sits under images/; labels mirror it.
    image_dir = next((p for p in images.rglob("*") if p.is_dir()), images)
    label_dir = Path(str(image_dir).replace("images", "labels", 1))
    return image_dir, label_dir


def _write_root(root: Path, stems: list[str], image_dir: Path, label_dir: Path) -> int:
    (root / "images").mkdir(parents=True, exist_ok=True)
    (root / "labels").mkdir(parents=True, exist_ok=True)
    (root / "classes.txt").write_text("\n".join(COCO_CLASSES) + "\n", encoding="utf-8")
    written = 0
    for stem in stems:
        image = next(image_dir.glob(f"{stem}.*"), None)
        if image is None:
            continue
        shutil.copy(image, root / "images" / image.name)
        label = label_dir / f"{stem}.txt"
        # An image with no objects has no label file; write an empty one.
        (root / "labels" / f"{stem}.txt").write_text(
            label.read_text(encoding="utf-8") if label.is_file() else "", encoding="utf-8"
        )
        written += 1
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Fetch COCO128 for LOFOP benchmarking.")
    parser.add_argument("--dest", type=Path, default=REPO_ROOT / "data" / "coco128")
    parser.add_argument("--val-fraction", type=float, default=0.2, help="portion held out for val")
    args = parser.parse_args(argv)

    raw = REPO_ROOT / "data" / "_coco128_raw"
    raw.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(io.BytesIO(_download(COCO128_URL))) as archive:
        archive.extractall(raw)

    image_dir, label_dir = _find_split_dirs(raw)
    stems = sorted(p.stem for p in image_dir.iterdir() if p.suffix.lower() in {".jpg", ".png"})
    if not stems:
        print("No images found in the COCO128 archive", file=sys.stderr)
        return 1
    split = max(1, int(len(stems) * (1 - args.val_fraction)))
    train_stems, val_stems = stems[:split], stems[split:] or stems[-1:]

    if args.dest.exists():
        shutil.rmtree(args.dest)
    n_train = _write_root(args.dest / "train", train_stems, image_dir, label_dir)
    n_val = _write_root(args.dest / "val", val_stems, image_dir, label_dir)

    config = REPO_ROOT / "configs" / "coco128.yaml"
    config.parent.mkdir(parents=True, exist_ok=True)
    config.write_text(
        "# Auto-generated by scripts/get_coco128.py. A 128-image COCO subset.\n"
        "data_format: yolo\n"
        f"train_source: {(args.dest / 'train').relative_to(REPO_ROOT)}\n"
        f"val_source: {(args.dest / 'val').relative_to(REPO_ROOT)}\n",
        encoding="utf-8",
    )
    shutil.rmtree(raw, ignore_errors=True)
    print(
        f"COCO128 ready: {n_train} train / {n_val} val images at {args.dest}\n"
        f"Config written to {config}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
